baseURL: https://talks.donsan.org
title: Security Talks Digest
theme: DoIt
enableEmoji: true
author:
  name: "David Sepashvili"
  email: "don-san-sec@pm.me"
  link: "https://donsan.org"

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1
    - identifier: posts
      name: Posts
      url: "/posts/"
      weight: 2
    - identifier: about
      name: About
      url: "/about/"
      weight: 99

params:
  version: 0.3.X
  title: Security Talks Digest
  description: Weekly digest of the security talks, categorised, summarised, and tagged
  fingerprint: sha512
  dateFormat: "2006-01-02"
  images: ["/logo.jpeg"]
  optimizeImages: true
  header:
    title:
      logo: "/android-chrome-256x256.png"
  home:
    profile:
      enable: True
      avatarUrl: /logo.jpeg
      avatarLinkURL: /about
      title: Security Talks Digest
      subtitle: Weekly digest of the security talks, categorised, summarised, and tagged
      typeit: False
      social: True
    posts:
      enable: True
  social:
    twitter:
      id: _security_talks
      weight: 10
    email:
      Template: ''
      URL: https://feedsubscription.com/to/security_talks
      weight: 20
    rss:
      weight: 30
    github:
      id: don-san-sec/security-talks
      weight: 40
  sponsor:
    enable: true
    bio: Want to express gratitude? Buy me a coffee.
    link: https://ko-fi.com/securitytalks
  footer:
    enable: True
    hugo: False
    author: true
    since: 2024
  cookieconsent:
    enable: False
  page:
    hiddenFromHomePage: False
    hiddenFromSearch: False
    twemoji: False
    lightgallery: False
    ruby: False
    fraction: False
    fontawesome: False
    linkToMarkdown: False
    linkToSource: False
    linkToEdit: False
    linkToReport: False
    rssFullText: True
    pageStyle: wide
    seriesNavigation: False
    toc:
      enable: True
      keepStatic: False
      auto: True
    math:
      enable: False
      copyTex: False
      mhchem: False
    code:
      copy: False
      maxShownLines: 10
    table:
      sort: False
    share:
      enable: False
    comment:
      enable: False
  twitterCard: # https://github.com/dereckcurry/hugo-configurable-twitter-cards
    generate: True
    card: "summary"
  analytics:
    enable: true
    umami:
      data_website_id: cad117fd-d112-4f24-8ba8-6b0f35969836
      src: https://eu.umami.is/script.js

markup:
  highlight:
    codeFences: True
    guessSyntax: True
    lineNos: True
    lineNumbersInTable: True
    noClasses: False
  goldmark:
    extensions:
      definitionList: True
      footnote: True
      linkify: True
      strikethrough: True
      table: True
      taskList: True
      typographer: True
    renderer:
      unsafe: True
    tableOfContents:
      startLevel: 2
      endLevel: 6