baseURL: https://talks.donsan.uk
title: Security Talks Digest
theme: DoIt
enableEmoji: true
author:
  name: "David Sepashvili"
  email: "don-san-sec@pm.me"
  link: "https://donsan.uk"

params:
  version: 0.3.X
  title: Security Talks Digest
  description: Weekly digest of the security talks, categorized, summarized, and tagged
  fingerprint: sha512
  dateFormat: "2006-01-02"
  images: ["/logo.jpeg"]
  optimizeImages: true
  header:
    title:
      name: Security Talks
      logo: "/android-chrome-256x256.png"
  home:
    profile:
      enable: True
      avatarUrl: /logo.jpeg
      title: Security Talks Digest
      subtitle: Weekly digest of the security talks, categorized, summarized, and tagged
      typeit: False
      social: True
    posts:
      enable: True
  social:
    ko-fi: securitytalks
    Twitter: donsansec
    Github: don-san-sec/security-talks
    RSS: true
  sponsor:
    enable: true
    bio: Want to express gratitude? Buy me a coffee.
    link: https://ko-fi.com/securitytalks


  footer:
    enable: True
    hugo: False
    author: true
    since: 2024
  cookieconsent:
    enable: False
  page:
    hiddenFromHomePage: False
    hiddenFromSearch: False
    twemoji: False
    lightgallery: False
    ruby: False
    fraction: False
    fontawesome: False
    linkToMarkdown: False
    linkToSource: False
    linkToEdit: False
    linkToReport: False
    rssFullText: True
    pageStyle: wide
    seriesNavigation: False
    toc:
      enable: True
      keepStatic: False
      auto: True
    math:
      enable: False
      copyTex: False
      mhchem: False
    code:
      copy: False
      maxShownLines: 10
    table:
      sort: False
    share:
      enable: False
    comment:
      enable: False
  twitterCard: # https://github.com/dereckcurry/hugo-configurable-twitter-cards
    generate: True
    card: "summary"

markup:
  highlight:
    codeFences: True
    guessSyntax: True
    lineNos: True
    lineNumbersInTable: True
    noClasses: False
  goldmark:
    extensions:
      definitionList: True
      footnote: True
      linkify: True
      strikethrough: True
      table: True
      taskList: True
      typographer: True
    renderer:
      unsafe: True
    tableOfContents:
      startLevel: 2
      endLevel: 6